Milestone 4: Style for desktop version with media queries
cnualartc/My_Portfolio pull request #5
Opened 2023-01-19 21:14 UTC by cnualartc

Used media queries to style the desktop version of the project.

2023-01-19 22:08 UTC, leonardodiasb requested changes
# Required Changes ♻️ ⚠️ 🚦 

Hi @cnualartc, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Good points 👍 

 - No linter errors. ✔️
 - Correct use of GitHub flow. ✔️ 

## Aspects to improve ♻️

- [x] Check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-19 22:08 UTC, leonardodiasb commented on index.html
> +        </div>
- [x] Your navbar is very similar to the Figma template. But the background color is not filling the entire navbar, and there are places with the correct white background color and other places with a gray background color making it not look similar to the template and not professional. Kindly make the whole navbar background white.
 - [x] Also the nav items are correctly wrapped with the `li` tags but they are also links to the sections of the page, so an `a` tag inside the `li` would be appropriate for this case. Kindly fix that.
 - Your design:
 - 
<img width="1035" alt="image" src="https://user-images.githubusercontent.com/61919617/213569846-811c1e6d-f341-4075-abcf-719f95577548.png">

2023-01-19 22:08 UTC, leonardodiasb commented on style.css
> +  }
- [ ] Your project cards are similar to the Figma template, but they are not responsive and on smaller screen sizes they are cut out off the screen. Please make them responsive so they can fit properly, maintaining the dimensions, on every screen size.
 - [ ] There are some areas inside the project card with different background colors. Please make them consistent and use the white background color for all the cards to match the Figma template.
 - [ ] The whole card has a cursor behavior as pointer, but when the user hovers over the button the cursor behavior is normal. This is inverted behavior. The expected behavior is to be pointer when the user hovers over the button and normal on the rest of the card so the user can know that that button is clickable. Kindly change that.
 - Your design:
 - 
<img width="959" alt="image" src="https://user-images.githubusercontent.com/61919617/213571742-b4ce8204-9eee-4649-8364-aea8bb7137d8.png">

2023-01-19 22:08 UTC, leonardodiasb commented on style.css
> +  }
- [ ] The about section is great and very similar, but there are some points that makes different from the template. First the background color of the about section should be white, to differentiate from the previous projects section background color and there should be a border radius on the top right corner. Kindly change that.
 - [ ] Also on smaller screen sizes, there is no padding on the sides of this section. Kindly add some padding to match the Template.
 - Your design:
 - 
<img width="969" alt="image" src="https://user-images.githubusercontent.com/61919617/213572523-14b4db0c-df3b-4003-b955-9a345c904a94.png">

 - Figma template:
 - 
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/61919617/213572671-2e948734-9ffb-4e4b-8df7-79e0bbe53bd1.png">

2023-01-21 00:01 UTC, emmiiorji approved these changes
Hi @cnualartc, 

# Status: Approved ✅

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Congrats](https://user-images.githubusercontent.com/20554583/213640109-3f8f3011-6232-4e65-b6ac-a60abca64de9.gif)

## Good Highlights✔️

- Linter checks are passing
- Good commit messages
- Proper use of GitHub flow
- Requested  changes have been implemented


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-21 01:43 UTC, merged